### ISSUE TITLE
Multiple cloud builds on the same directory

### ISSUE THREAD

**Issue by jfri3d** [KI-labs/kaos#20]
#### What is the desired change?

When multiple builds are performed for different contexts (environments) in the same kaos home directory, clear and separate abstractions need to be created for these contexts in the form of separate environment specific directories (DOCKER/AWS/GCP) which would then store the associated terraform state files within them.

#### How will this change improve kaos?

Ensure that multiple backends can be built within a single directory with clear separation between the ENVs.

#### Any thoughts on the implementation approach?

A separate directory within `.kaos/` for all terraform state files.

**Comment by ms-shankar** [comment]
Handled in the following PR:

https://github.com/KI-labs/kaos/pull/49
