### ISSUE TITLE
check local port collision (i.e. port 80)

### ISSUE THREAD

**Issue by jfri3d** [KI-labs/kaos#28]
#### What is the desired change?

Local deployment requires a rather clean ENV - hampered by port collisions. kaos is not able to connect to a running local cluster backend if another service is running on port 80. 

> this is **only** related to `DOCKER` deployment.

#### How will this change improve kaos?

Less critical issue but has caused errors when another service is running on port 80.

#### Any thoughts on the implementation approach?

* check port 80 collisions when running `kaos build -c DOCKER`
* issue warning if another service is running

**Comment by aalhour** [comment]
Just opened the PR #59 to implement this feature.
